name: Docker Image CI

on:
  push:
    branches: [ "main" ] # none
  pull_request:
    branches: none #[ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/efficacy38/pj-base:$(date +%s)
